# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_auto_20161210_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_category', models.BooleanField()),
                ('bot_sib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_sib_to_self', to='menu_app.MenuTree')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_tree_to_category', to='menu_app.Category')),
                ('first_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_child_to_self', to='menu_app.MenuTree')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_to_self', to='menu_app.MenuTree')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_tree_product', to='menu_app.Product')),
                ('top_sib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_sib_to_self', to='menu_app.MenuTree')),
            ],
        ),
    ]
