# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_menutree'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutree',
            name='child_qty',
            field=models.IntegerField(default=0),
        ),
    ]
