# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_menutree_child_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutree',
            name='child_qty_active',
            field=models.IntegerField(default=0),
        ),
    ]
